services:
  app:
    image: belakang-toko-app
    build:
      args:
        user: kentang
        uid: 1000
      context: ./
      dockerfile: Dockerfile.dev

    container_name: belakang-toko-app
    working_dir: /var/www
    restart: unless-stopped

    environment:
      COMPOSER_MEMORY_LIMIT: -1

    volumes:
      - ./:/var/www
      - laravel_storage:/var/www/storage
      - laravel_cache:/var/www/bootstrap/cache

    networks:
      - kentangnet

    depends_on:
      - redis


  # DATABASE DOCKER DISABLED
  # Laravel menggunakan database external:
  # host.docker.internal:3306
  #
  # db:
  #   image: mysql/mysql-server:5.7
  #   platform: linux/amd64
  #   container_name: mysql_tokobangunan
  #   restart: unless-stopped
  #
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE:-local_laravel}
  #     MYSQL_USER: ${DB_USERNAME:-local_developer}
  #     MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
  #
  #   ports:
  #     - "3344:3306"
  #
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #     - ./docker-compose/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  #
  #   networks:
  #     - kentangnet


  nginx:
    image: nginx:alpine
    container_name: nginx_tokobangunan
    restart: unless-stopped

    depends_on:
      - app

    ports:
      - "8183:80"

    volumes:
      - ./:/var/www:ro
      - laravel_storage:/var/www/storage:ro
      - ./docker-compose/nginx:/etc/nginx/conf.d:ro

    networks:
      - kentangnet


  redis:
    image: redis:7
    container_name: redis-server
    restart: unless-stopped

    volumes:
      - redis_data:/data

    ports:
      - "26739:6379"

    networks:
      - kentangnet


  scheduler:
    image: belakang-toko-app
    container_name: belakang-toko-scheduler
    restart: unless-stopped

    command: ["php", "artisan", "schedule:work"]

    depends_on:
      - app
      - redis

    volumes:
      - ./:/var/www
      - laravel_storage:/var/www/storage
      - laravel_cache:/var/www/bootstrap/cache

    env_file:
      - .env

    networks:
      - kentangnet


volumes:
  redis_data:
  laravel_storage:
  laravel_cache:


networks:
  kentangnet:
    driver: bridge
